// Automatically generated by astro-icon
// 543e6c6b474aeee2d2ad4d33c82b46d5e3b5ed0752eef9ab4bd78adb00824c8d

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "email"
		| "github"
		| "googlescholar"
		| "linkedin"
		| "researchgate";
}